@echo off
echo Verificando e corrigindo erros no disco...
chkdsk C: /f /r
echo Verificacao de arquivos corrompidos em andamento...
sfc /scannow
echo Verificando a integridade da imagem do sistema...
DISM /Online /Cleanup-Image /RestoreHealth
echo Limpando arquivos temporarios...
del /q/f/s %TEMP%\*
echo Limpando cache do DNS...
ipconfig /flushdns
echo Finalizando programas nao essenciais...
tasklist
echo Finalize os processos manualmente ou adicione o comando taskkill com o nome do processo aqui
echo Desfragmentando disco...
defrag C: /O
echo Verificando espaco em disco...
wmic logicaldisk get size,freespace,caption
echo Alterando para plano de energia de alto desempenho...
powercfg /s SCHEME_MIN
echo Todas as tarefas foram concluídas!
pause
